server:
  ssl:
    enabled: true
    key-store: src/main/resources/identity.jks
    key-password: secret
    key-store-password: secret
    trust-store: src/main/resources/truststore.jks
    trust-store-password: secret
