management:
  endpoint:
    routes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1:8761/eureka,http://eureka2:8761/eureka

spring:
  application:
    name: zuul-server

server:
    port: 8771
    ssl:
      enabled: true
      key-store: home/identity.jks
      key-password: secret123
      key-store-password: secret123
      trust-store: home/truststore.jks
      trust-store-password: secret123
      client-auth: need
