management:
  endpoint:
    routes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka

spring:
  application:
    name: zuul-server
---
spring:
  profiles: peer1
server:
  port: 8771
---
spring:
  profiles: peer2
server:
  port: 8772